version: "3"

services:
  web:
    build:
      context: ./services/web
      target: ci

  auth:
    build:
      context: ./services/auth
      target: ci

  status:
    build:
      context: ./services/status
      target: ci

  docs:
    build:
      context: ./docs
      target: ci
