version: "3"

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.dev
    environment:
      - PORT=80
      - HOST=web
    networks:
      - network
    volumes:
      - ./services/web:/app
      - /app/node_modules

  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile.dev
    environment:
      - PORT=80
      - HOST=auth
      - DATABASE_URL=postgresql://auth:auth@auth-db:5432/dev
    networks:
      - network
    volumes:
      - ./services/auth:/app
      - /app/node_modules
  
  auth-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=auth
      - POSTGRES_USER=auth
      - POSTGRES_DB=dev
    networks:
      - network
    volumes:
      - ./persistence/auth/db:/var/lib/postgresql/data
  
  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile.dev
    environment:
      - PORT=80
      - HOST=users
    networks:
      - network
    volumes:
      - ./services/users:/app
      - /app/node_modules

  status:
    build:
      context: ./services/status
      dockerfile: Dockerfile.dev
    environment:
      - PORT=80
      - HOST=status
    networks:
      - network
    volumes:
      - ./services/status:/app
      - /app/node_modules

  gateway:
    build: ./gateway
    env_file:
      - .env.dev
    ports:
      - "${APP_PORT}:80"
    networks:
      - network

networks:
  network:
    driver: bridge
