version: "3"

services:
  web:
    build: ./services/web
    environment:
      - PORT=80
      - HOST=web
    networks:
      - network
  
  facilities:
    build: ./services/facilities
    environment:
      - FLASK_RUN_PORT=80
      - FLASK_RUN_HOST=facilities
    networks:
      - network

  gateway:
    build: ./gateway
    env_file:
      - .env
    ports:
      - "${APP_PORT}:80"
    networks:
      - network

networks:
  network:
    driver: bridge
