version: "3"

services:
  web:
    build: ./services/web
    environment:
      - PORT=80
      - HOST=web
    networks:
      - network

  auth:
    build: ./services/auth
    environment:
      - PORT=80
      - HOST=auth
      - DATABASE_URL=mongodb://auth-db:27017/prod
    networks:
      - network
  
  auth-db:
    image: mongo
    restart: always
    networks:
      - network
    volumes:
      - ./persistence/auth/db:/data/db

  status:
    build: ./services/status
    environment:
      - PORT=80
      - HOST=status
    networks:
      - network

  users:
    build: ./services/users
    environment:
      - PORT=80
      - HOST=users
    networks:
      - network
  
  gateway:
    build: ./gateway
    env_file:
      - .env
    ports:
      - "${APP_PORT}:80"
    networks:
      - network

networks:
  network:
    driver: bridge
