version: "3"

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.dev
    environment:
      - PORT=80
      - HOST=web
    networks:
      - network
    volumes:
      - ./services/web:/app
      - /app/node_modules

  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile.dev
    environment:
      - PORT=80
      - HOST=auth
    networks:
      - network
    volumes:
      - ./services/auth:/app
      - /app/node_modules
  
  status:
    build:
      context: ./services/status
      dockerfile: Dockerfile.dev
    environment:
      - PORT=80
      - HOST=status
    networks:
      - network
    volumes:
      - ./services/status:/app
      - /app/node_modules

  gateway:
    build: ./gateway
    env_file:
      - .env.dev
    ports:
      - "${APP_PORT}:80"
    networks:
      - network

networks:
  network:
    driver: bridge
