version: "3"

services:
  web:
    build: ./services/web
    environment:
      - PORT=80
      - HOST=web
    networks:
      - network

  auth:
    build: ./services/auth
    environment:
      - PORT=80
      - HOST=auth
      - DATABASE_URL=postgresql://auth:auth@auth-db:5432/dev
    networks:
      - network
  
  auth-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=auth
      - POSTGRES_USER=auth
      - POSTGRES_DB=dev
    networks:
      - network
    volumes:
      - ./persistence/auth/db:/var/lib/postgresql/data

  status:
    build: ./services/status
    environment:
      - PORT=80
      - HOST=status
    networks:
      - network

  users:
    build: ./services/users
    environment:
      - PORT=80
      - HOST=users
    networks:
      - network
  
  gateway:
    build: ./gateway
    env_file:
      - .env
    ports:
      - "${APP_PORT}:80"
    networks:
      - network

networks:
  network:
    driver: bridge
