version: "3"

services:
  web:
    build:
      context: ./services/web
      target: ci

  auth:
    build:
      context: ./services/auth
      target: ci

  status:
    build:
      context: ./services/status
      target: ci

  users:
    build:
      context: ./services/users
      target: ci
    environment:
      - APP_PORT=${APP_PORT}
      - JWT_SIGNING_SECRET=${AUTH_JWT_SIGNING_SECRET}

  docs:
    build:
      context: ./docs
      target: ci
