version: "3"

services:
  web:
    build: ./services/web
    environment:
      - PORT=80
      - HOST=web
    networks:
      - network

  auth:
    build: ./services/auth
    environment:
      - PORT=80
      - HOST=auth
    env_file:
      - .env
    ports:
      - "${APP_PORT}:80"
    networks:
      - network

  gateway:
    build: ./gateway
    env_file:
      - .env
    ports:
      - "${APP_PORT}:80"
    networks:
      - network

networks:
  network:
    driver: bridge
