version: "3"

services:
  auth:
    build:
      context: ./services/auth
      target: ci

  status:
    build:
      context: ./services/status
      target: ci

  docs:
    build:
      context: ./docs
      target: ci

  payments:
    build:
      context: ./services/payments
      target: ci
    environment:
      - STRIPE_API=${STRIPE_API}
      - APP_PORT=${APP_PORT}

  management:
    build:
      context: ./services/management
      target: ci
