"""added description to facilities

Revision ID: 2c8eba127543
Revises: 6b73092b76c3
Create Date: 2023-03-24 10:50:49.458721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c8eba127543'
down_revision = '6b73092b76c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facility', sa.Column('description', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facility', 'description')
    # ### end Alembic commands ###
