"""added name to activity

Revision ID: d7565a6aa38e
Revises: ff1f66cb3bf0
Create Date: 2023-03-06 13:06:38.124035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7565a6aa38e'
down_revision = 'ff1f66cb3bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'name')
    # ### end Alembic commands ###
