name: Booking Microservice CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  test-booking-microservice:
    runs-on: ubuntu-latest
    env:
      HOST: localhost
      PORT: 12345
      DEBUG: true
      DATABASE_URL: file:./dev.db

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./services/booking

      - name: Run linter
        run: pnpm run lint
        working-directory: ./services/booking

      - name: Build
        run: pnpm run build
        working-directory: ./services/booking

      - name: Push Database
        run: pnpm run db:push
        working-directory: ./services/booking

      - name: Test
        run: pnpm run test
        working-directory: ./services/booking
