name: Continuous Integration

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  web-ci-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install pnpm
        run: npm install -g pnpm
        working-directory: ./services/web

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./services/web

      - name: Lint code base with GTS
        run: pnpm run ci
        working-directory: ./services/web

  auth-ci-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run ci tests in docker
        run: make ci-auth

  docs-ci-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run ci tests in docker
        run: make ci-docs

  status-ci-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run ci tests in docker
        run: make ci-status

  facilities-ci-checls:
    runs-ci-checks:
      strategy:
        matrix:
          python-version: ["3.9", "3.10"]

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}

        - name: Setup env
          run: make setup-dev
          working-directory: ./services/facilities

        - name: Update env
          run: make update-env
          working-directory: ./services/facilities

        - name: Run tests
          run: make test
          working-directory: ./services/facilities
